### ISSUE TITLE
[BUG] wapi_set_ifdown failed

### ISSUE THREAD

**Issue by metarutaiga** [apache/nuttx-apps#2505] opened 2024-08-19 12:09 UTC
### Description / Steps to reproduce the issue

https://github.com/apache/nuttx-apps/blob/9bfe138087ebc1d2439aeb252b6b26e347ad9759/wireless/wapi/src/network.c#L250

It miss to set IFF_DOWN into ifr.ifr_flags;
```
       ifr.ifr_flags &= ~IFF_UP;
+      ifr.ifr_flags |= IFF_DOWN;
```

And look at this
https://github.com/apache/nuttx-apps/blob/21f5bc9b70b1b4bb356a7be7de158e1919f6e989/netutils/netlib/netlib_setifstatus.c#L121

### On which OS does this issue occur?

[Mac]

### What is the version of your OS?

macOS 14

### NuttX Version

12.6.0

### Issue Architecture

[risc-v]

### Issue Area

[Networking]

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment] 2024-09-19 15:41
@tmedicci what do you think? Is this modification correct?

**Comment by xiaoxiang781216** [comment] 2024-10-07 11:03
@acassis @metarutaiga the problem is fixed by https://github.com/apache/nuttx-apps/pull/2647 and https://github.com/apache/nuttx/pull/13842.

**Closed** 2024-10-07 12:19 UTC
Labels: Type: Bug, OS: Mac, Arch: risc-v, Area: Networking
